#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 31 11:58:43 2018

@author: Luis M. Colon-Perez, PhD

Script to rename files as they are generated from flywheel

"""
import os
import glob
import shutil

# data_index equal to: 0 for dwi_data; 1 for t1_data; 2 for resting state fMRI
data_index = 2
# rem = 1; to delete flywheel directory or any other number to keep it
rem = 1
# main directory to data inputs and outputs
experiment_dir = '/home/luiscp/Documents/Data/'
# data output directory, if it does not exists it will creasted in experiment_dir
fileodir='ADRC_90Plus/'
# subject id as it appears in the input directory
nameofsubjects = ['250','251','253','254','256','257','259']
#nameofsubjects = ['233','234','235','236','237','238','239','240','242','243','244','245','246','248','249','250','251','253','254','256','257','259']

# identify input directory as is generated by flywheel
os.chdir(experiment_dir)
fileidir=glob.glob('flywheel_*/yassalab/ADRC_90Plus/')
fileidir=''.join(map(str, fileidir))
##############################
# Start renaming
##############################

fileidir=''.join(map(str, fileidir))
if not os.path.exists(experiment_dir+fileodir):
            os.mkdir(experiment_dir+fileodir)

def dwi_data():
    count = 0
    filenpre='/Brain_ADRC_Proj_1-90/'
    while count < len(nameofsubjects):
        print(nameofsubjects[count])
        
        fileoutdir=experiment_dir+fileodir+'sub_'+nameofsubjects[count]
        if not os.path.exists(fileoutdir):
            os.mkdir(fileoutdir)
            
        filename=fileoutdir+'/b0_PA.nii.gz'
        if not os.path.exists(filename):
            filen=glob.glob(experiment_dir+fileidir+nameofsubjects[count]+filenpre+'diff_HCPish_PA_b0/*.nii.gz')
            filen=''.join(map(str, filen))
            os.rename(filen, filename)
        
        filename=fileoutdir+'/b0_AP.nii.gz'
        if not os.path.exists(filename):
            filen=glob.glob(experiment_dir+fileidir+nameofsubjects[count]+filenpre+'diff_HCPish_AP_b0/*.nii.gz')
            filen=''.join(map(str, filen))
            os.rename(filen, filename )
        
        filename=fileoutdir+'/data.bval'
        if not os.path.exists(filename):
            filen=glob.glob(experiment_dir+fileidir+nameofsubjects[count]+filenpre+'diff_HCPish_AP/*.bval')
            filen=''.join(map(str, filen))
            os.rename(filen, filename) 
        
        filename=fileoutdir+'/data.bvec'
        if not os.path.exists(filename):
            filen=glob.glob(experiment_dir+fileidir+nameofsubjects[count]+filenpre+'diff_HCPish_AP/*.bvec')
            filen=''.join(map(str, filen))
            os.rename(filen, filename)
        
        filename=fileoutdir+'/data.nii.gz'
        if not os.path.exists(filename):
            filen=glob.glob(experiment_dir+fileidir+nameofsubjects[count]+filenpre+'diff_HCPish_AP/*.nii.gz')
            filen=''.join(map(str, filen))
            os.rename(filen, filename) 
        
        count+= 1
    return

def t1_data():
    count=0
    filenpre='/Brain_ADRC_Proj_1-90/0.8mm_TR2.3_t1_mprage/'
    while count < len(nameofsubjects):
        print(nameofsubjects[count])
        fileoutdir=experiment_dir+fileodir+'sub_'+nameofsubjects[count]
        if not os.path.exists(fileoutdir):
            os.mkdir(fileoutdir)
        filename=fileoutdir+'/t1_mprage.nii.gz'
        if not os.path.exists(filename):
            filen=glob.glob(experiment_dir+fileidir+nameofsubjects[count]+filenpre+'*.nii.gz')
            filen=''.join(map(str, filen))
            fileoutdir=experiment_dir+fileodir+'sub_'+nameofsubjects[count]
            os.rename(filen,filename )
        count+= 1
    return

def rs_data():
    count=0
    filenpre='/Brain_ADRC_Proj_1-90/rsfMRI_Yassa_Philips_Zach_BOLD/'
    while count < len(nameofsubjects):
        print(nameofsubjects[count])
        fileoutdir=experiment_dir+fileodir+'sub_'+nameofsubjects[count]
        if not os.path.exists(fileoutdir):
            os.mkdir(fileoutdir)
        filename=fileoutdir+'/rsfMRI.nii.gz'
        if not os.path.exists(filename):
            filen=glob.glob(experiment_dir+fileidir+nameofsubjects[count]+filenpre+'*.nii.gz')
            filen=''.join(map(str, filen))
            fileoutdir=experiment_dir+fileodir+'sub_'+nameofsubjects[count]
            os.rename(filen,filename )
        count+= 1
    return

switcher={
        0:dwi_data,
        1:t1_data,
        2:rs_data
        } 

def numbers_to_datatype(argument):
    func = switcher.get(argument, "no data type")
    return func()

numbers_to_datatype(data_index)

if rem == 1:
    filermdir=glob.glob(experiment_dir+'flywheel_*/')
    filermdir=''.join(map(str, filermdir))
    shutil.rmtree(filermdir)